// ── Hlavné oceánske prúdy ────────────────────────────────────────
// Orientačné referenčné dáta (typický smer/priemerná rýchlosť), zostavené
// podľa všeobecne známych údajov z pilotných máp (Pilot Charts / Ocean
// Current Atlas). Cesty sú zjednodušené polylines (2-6 bodov) – NIE
// navigačne presné, prúdy reálne kolíšu sezónne aj medziročne. Poradie
// bodov v `path` udáva smer toku.

/// Jeden bod (lat, lon) na trase prúdu.
typedef CurrentPoint = ({double lat, double lon});

class OceanCurrent {
  final String id;
  final String nameEn, nameSk, nameDe, nameEs, nameUk;
  final List<CurrentPoint> path;
  final double speedKtMin, speedKtMax;
  final String noteEn, noteSk, noteDe, noteEs, noteUk;

  const OceanCurrent({
    required this.id,
    required this.nameEn, required this.nameSk, required this.nameDe,
    required this.nameEs, required this.nameUk,
    required this.path,
    required this.speedKtMin, required this.speedKtMax,
    required this.noteEn, required this.noteSk, required this.noteDe,
    required this.noteEs, required this.noteUk,
  });

  String name(String languageCode) => switch (languageCode) {
        'sk' => nameSk, 'de' => nameDe, 'es' => nameEs, 'uk' => nameUk,
        _ => nameEn,
      };

  String note(String languageCode) => switch (languageCode) {
        'sk' => noteSk, 'de' => noteDe, 'es' => noteEs, 'uk' => noteUk,
        _ => noteEn,
      };
}

const oceanCurrents = <OceanCurrent>[
  OceanCurrent(
    id: 'gulf_stream',
    nameEn: 'Gulf Stream', nameSk: 'Golfský prúd', nameDe: 'Golfstrom',
    nameEs: 'Corriente del Golfo', nameUk: 'Гольфстрім',
    path: [
      (lat: 25.5, lon: -80.1), (lat: 30.0, lon: -79.0),
      (lat: 35.0, lon: -74.0), (lat: 40.0, lon: -65.0),
      (lat: 45.0, lon: -45.0), (lat: 50.0, lon: -25.0),
    ],
    speedKtMin: 2.5, speedKtMax: 4.5,
    noteEn: 'Warm current, Florida Straits north along US East Coast, then east across the North Atlantic. Year-round.',
    noteSk: 'Teplý prúd, z Floridského prielivu na sever pozdĺž východného pobrežia USA, potom na východ cez sev. Atlantik. Celoročne.',
    noteDe: 'Warmer Strom, von der Floridastraße nordwärts entlang der US-Ostküste, dann ostwärts über den Nordatlantik. Ganzjährig.',
    noteEs: 'Corriente cálida, desde el Estrecho de Florida hacia el norte por la costa este de EE.UU., luego al este por el Atlántico Norte. Todo el año.',
    noteUk: 'Тепла течія від Флоридської протоки на північ уздовж східного узбережжя США, потім на схід через Північну Атлантику. Цілий рік.',
  ),
  OceanCurrent(
    id: 'north_atlantic_drift',
    nameEn: 'North Atlantic Drift', nameSk: 'Severoatlantický prúd', nameDe: 'Nordatlantikstrom',
    nameEs: 'Corriente del Atlántico Norte', nameUk: 'Північноатлантична течія',
    path: [(lat: 45.0, lon: -35.0), (lat: 50.0, lon: -20.0), (lat: 55.0, lon: -10.0), (lat: 58.0, lon: 0.0)],
    speedKtMin: 0.5, speedKtMax: 1.5,
    noteEn: 'Continuation of the Gulf Stream toward NW Europe; keeps European coasts mild. Year-round.',
    noteSk: 'Pokračovanie Golfského prúdu smerom k severozápadnej Európe; udržiava mierne pobrežie Európy. Celoročne.',
    noteDe: 'Fortsetzung des Golfstroms Richtung Nordwesteuropa; hält europäische Küsten mild. Ganzjährig.',
    noteEs: 'Continuación de la Corriente del Golfo hacia el noroeste de Europa; mantiene templadas las costas europeas. Todo el año.',
    noteUk: 'Продовження Гольфстріму до Північно-Західної Європи; пом\'якшує клімат узбережжя Європи. Цілий рік.',
  ),
  OceanCurrent(
    id: 'canary_current',
    nameEn: 'Canary Current', nameSk: 'Kanársky prúd', nameDe: 'Kanarenstrom',
    nameEs: 'Corriente de Canarias', nameUk: 'Канарська течія',
    path: [(lat: 40.0, lon: -10.0), (lat: 30.0, lon: -12.0), (lat: 20.0, lon: -17.0), (lat: 12.0, lon: -18.0)],
    speedKtMin: 0.3, speedKtMax: 0.8,
    noteEn: 'Cool current down the NW African coast, feeding the North Equatorial Current. Year-round.',
    noteSk: 'Studený prúd popri severozápadnom pobreží Afriky, napája Severný rovníkový prúd. Celoročne.',
    noteDe: 'Kalter Strom entlang der nordwestafrikanischen Küste, speist den Nordäquatorialstrom. Ganzjährig.',
    noteEs: 'Corriente fría a lo largo de la costa noroeste de África, alimenta la Corriente Ecuatorial del Norte. Todo el año.',
    noteUk: 'Холодна течія вздовж північно-західного узбережжя Африки, живить Північну екваторіальну течію. Цілий рік.',
  ),
  OceanCurrent(
    id: 'north_equatorial_atlantic',
    nameEn: 'North Equatorial Current (Atlantic)', nameSk: 'Severný rovníkový prúd (Atlantik)',
    nameDe: 'Nordäquatorialstrom (Atlantik)', nameEs: 'Corriente Ecuatorial del Norte (Atlántico)',
    nameUk: 'Північна екваторіальна течія (Атлантика)',
    path: [(lat: 15.0, lon: -20.0), (lat: 13.0, lon: -40.0), (lat: 11.0, lon: -60.0)],
    speedKtMin: 0.5, speedKtMax: 1.0,
    noteEn: 'Westward flow across the tropical Atlantic toward the Caribbean. Year-round.',
    noteSk: 'Prúdenie na západ cez tropický Atlantik smerom ku Karibiku. Celoročne.',
    noteDe: 'Westströmung durch den tropischen Atlantik Richtung Karibik. Ganzjährig.',
    noteEs: 'Flujo hacia el oeste a través del Atlántico tropical hacia el Caribe. Todo el año.',
    noteUk: 'Течія на захід через тропічну Атлантику до Карибського басейну. Цілий рік.',
  ),
  OceanCurrent(
    id: 'loop_current',
    nameEn: 'Loop Current (Gulf of Mexico)', nameSk: 'Loop Current (Mexický záliv)',
    nameDe: 'Loop Current (Golf von Mexiko)', nameEs: 'Corriente del Lazo (Golfo de México)',
    nameUk: 'Петлева течія (Мексиканська затока)',
    path: [(lat: 21.5, lon: -85.0), (lat: 25.0, lon: -87.0), (lat: 27.0, lon: -84.0), (lat: 24.5, lon: -81.5)],
    speedKtMin: 1.5, speedKtMax: 3.5,
    noteEn: 'Enters via Yucatan Channel, loops in the Gulf, exits through the Florida Straits into the Gulf Stream. Year-round, position varies.',
    noteSk: 'Vstupuje cez Yucatanský prieliv, tvorí slučku v zálive, vystupuje cez Floridský prieliv do Golfského prúdu. Celoročne, poloha kolíše.',
    noteDe: 'Tritt durch die Yucatan-Straße ein, bildet eine Schleife im Golf, verlässt ihn durch die Floridastraße in den Golfstrom. Ganzjährig, Lage variiert.',
    noteEs: 'Entra por el Canal de Yucatán, forma un lazo en el golfo, sale por el Estrecho de Florida hacia la Corriente del Golfo. Todo el año, posición variable.',
    noteUk: 'Входить через Юкатанську протоку, утворює петлю в затоці, виходить через Флоридську протоку в Гольфстрім. Цілий рік, позиція змінюється.',
  ),
  OceanCurrent(
    id: 'labrador_current',
    nameEn: 'Labrador Current', nameSk: 'Labradorský prúd', nameDe: 'Labradorstrom',
    nameEs: 'Corriente del Labrador', nameUk: 'Лабрадорська течія',
    path: [(lat: 60.0, lon: -62.0), (lat: 52.0, lon: -55.0), (lat: 45.0, lon: -50.0)],
    speedKtMin: 0.4, speedKtMax: 1.0,
    noteEn: 'Cold current from Baffin Bay south past Newfoundland/Grand Banks; brings icebergs. Year-round, strongest spring.',
    noteSk: 'Studený prúd z Baffinovho zálivu na juh popri Newfoundlande/Grand Banks; prináša ľadovce. Celoročne, najsilnejší na jar.',
    noteDe: 'Kalter Strom von der Baffin Bay südwärts an Neufundland/Grand Banks vorbei; bringt Eisberge. Ganzjährig, am stärksten im Frühjahr.',
    noteEs: 'Corriente fría desde la Bahía de Baffin hacia el sur pasando Terranova/Grand Banks; trae icebergs. Todo el año, más fuerte en primavera.',
    noteUk: 'Холодна течія від затоки Баффіна на південь повз Ньюфаундленд/Великі Лави; несе айсберги. Цілий рік, найсильніша навесні.',
  ),
  OceanCurrent(
    id: 'brazil_current',
    nameEn: 'Brazil Current', nameSk: 'Brazílsky prúd', nameDe: 'Brasilstrom',
    nameEs: 'Corriente de Brasil', nameUk: 'Бразильська течія',
    path: [(lat: -5.0, lon: -35.0), (lat: -20.0, lon: -40.0), (lat: -35.0, lon: -50.0)],
    speedKtMin: 0.5, speedKtMax: 1.5,
    noteEn: 'Warm current flowing south along the Brazilian coast. Year-round.',
    noteSk: 'Teplý prúd tečúci na juh pozdĺž brazílskeho pobrežia. Celoročne.',
    noteDe: 'Warmer Strom entlang der brasilianischen Küste südwärts. Ganzjährig.',
    noteEs: 'Corriente cálida que fluye hacia el sur a lo largo de la costa brasileña. Todo el año.',
    noteUk: 'Тепла течія, що прямує на південь уздовж узбережжя Бразилії. Цілий рік.',
  ),
  OceanCurrent(
    id: 'benguela_current',
    nameEn: 'Benguela Current', nameSk: 'Benguelský prúd', nameDe: 'Benguelastrom',
    nameEs: 'Corriente de Benguela', nameUk: 'Бенгельська течія',
    path: [(lat: -34.0, lon: 17.5), (lat: -25.0, lon: 13.5), (lat: -15.0, lon: 10.0)],
    speedKtMin: 0.3, speedKtMax: 0.8,
    noteEn: 'Cold current north along the SW African coast (Namibia/Angola). Year-round.',
    noteSk: 'Studený prúd na sever pozdĺž juhozápadného pobrežia Afriky (Namíbia/Angola). Celoročne.',
    noteDe: 'Kalter Strom nordwärts entlang der südwestafrikanischen Küste (Namibia/Angola). Ganzjährig.',
    noteEs: 'Corriente fría hacia el norte por la costa suroeste de África (Namibia/Angola). Todo el año.',
    noteUk: 'Холодна течія на північ уздовж південно-західного узбережжя Африки (Намібія/Ангола). Цілий рік.',
  ),
  OceanCurrent(
    id: 'gibraltar_inflow',
    nameEn: 'Strait of Gibraltar Inflow', nameSk: 'Prítok cez Gibraltársky prieliv',
    nameDe: 'Einstrom Straße von Gibraltar', nameEs: 'Entrada del Estrecho de Gibraltar',
    nameUk: 'Приплив через Гібралтарську протоку',
    path: [(lat: 36.0, lon: -5.6), (lat: 36.1, lon: -4.5), (lat: 36.5, lon: -3.0)],
    speedKtMin: 1.0, speedKtMax: 3.0,
    noteEn: 'Surface Atlantic water flows east into the Mediterranean (Alboran Sea gyre); a deep return current flows out below. Year-round.',
    noteSk: 'Povrchová atlantická voda prúdi na východ do Stredozemného mora (vír Alboránskeho mora); hlboký spätný prúd tečie pod ňou von. Celoročne.',
    noteDe: 'Atlantisches Oberflächenwasser strömt ostwärts ins Mittelmeer (Alboran-Wirbel); darunter fließt ein tiefer Rückstrom hinaus. Ganzjährig.',
    noteEs: 'El agua atlántica superficial fluye hacia el este al Mediterráneo (giro del Mar de Alborán); una corriente de retorno profunda sale por debajo. Todo el año.',
    noteUk: 'Поверхнева атлантична вода тече на схід у Середземне море (вир моря Альборан); глибинна зворотна течія тече назовні під нею. Цілий рік.',
  ),
  OceanCurrent(
    id: 'kuroshio',
    nameEn: 'Kuroshio Current', nameSk: 'Prúd Kuroshio', nameDe: 'Kuroshio-Strom',
    nameEs: 'Corriente de Kuroshio', nameUk: 'Течія Куросіо',
    path: [(lat: 20.0, lon: 122.0), (lat: 28.0, lon: 129.0), (lat: 35.0, lon: 140.0), (lat: 40.0, lon: 148.0)],
    speedKtMin: 2.0, speedKtMax: 3.5,
    noteEn: 'Warm current from Taiwan/Philippines north along Japan, then turning east. Year-round, Pacific counterpart of the Gulf Stream.',
    noteSk: 'Teplý prúd z Taiwanu/Filipín na sever pozdĺž Japonska, potom sa stáča na východ. Celoročne, tichomorský náprotivok Golfského prúdu.',
    noteDe: 'Warmer Strom von Taiwan/Philippinen nordwärts entlang Japans, dann ostwärts abbiegend. Ganzjährig, pazifisches Gegenstück zum Golfstrom.',
    noteEs: 'Corriente cálida desde Taiwán/Filipinas hacia el norte a lo largo de Japón, luego gira al este. Todo el año, contraparte pacífica de la Corriente del Golfo.',
    noteUk: 'Тепла течія від Тайваню/Філіппін на північ уздовж Японії, потім повертає на схід. Цілий рік, тихоокеанський аналог Гольфстріму.',
  ),
  OceanCurrent(
    id: 'oyashio',
    nameEn: 'Oyashio Current', nameSk: 'Prúd Oyashio', nameDe: 'Oyashio-Strom',
    nameEs: 'Corriente de Oyashio', nameUk: 'Течія Оясіо',
    path: [(lat: 55.0, lon: 160.0), (lat: 45.0, lon: 155.0), (lat: 38.0, lon: 145.0)],
    speedKtMin: 0.3, speedKtMax: 0.7,
    noteEn: 'Cold current from the Bering Sea south along Kamchatka/Kuril Islands to NE Japan. Year-round.',
    noteSk: 'Studený prúd z Beringovho mora na juh pozdĺž Kamčatky/Kurilských ostrovov k severovýchodnému Japonsku. Celoročne.',
    noteDe: 'Kalter Strom von der Beringsee südwärts entlang Kamtschatka/Kurilen bis Nordost-Japan. Ganzjährig.',
    noteEs: 'Corriente fría desde el Mar de Bering hacia el sur a lo largo de Kamchatka/Islas Kuriles hasta el noreste de Japón. Todo el año.',
    noteUk: 'Холодна течія від Берингового моря на південь уздовж Камчатки/Курильських островів до північного сходу Японії. Цілий рік.',
  ),
  OceanCurrent(
    id: 'california_current',
    nameEn: 'California Current', nameSk: 'Kalifornský prúd', nameDe: 'Kalifornienstrom',
    nameEs: 'Corriente de California', nameUk: 'Каліфорнійська течія',
    path: [(lat: 48.0, lon: -126.0), (lat: 38.0, lon: -124.0), (lat: 28.0, lon: -117.0), (lat: 20.0, lon: -110.0)],
    speedKtMin: 0.3, speedKtMax: 0.7,
    noteEn: 'Cool current south along the US West Coast toward Baja California. Year-round, strongest in summer.',
    noteSk: 'Studený prúd na juh pozdĺž západného pobrežia USA smerom k Baja California. Celoročne, najsilnejší v lete.',
    noteDe: 'Kalter Strom südwärts entlang der US-Westküste Richtung Baja California. Ganzjährig, am stärksten im Sommer.',
    noteEs: 'Corriente fría hacia el sur por la costa oeste de EE.UU. hacia Baja California. Todo el año, más fuerte en verano.',
    noteUk: 'Холодна течія на південь уздовж західного узбережжя США до Нижньої Каліфорнії. Цілий рік, найсильніша влітку.',
  ),
  OceanCurrent(
    id: 'humboldt_current',
    nameEn: 'Humboldt (Peru) Current', nameSk: 'Humboldtov (Peruánsky) prúd',
    nameDe: 'Humboldtstrom (Perustrom)', nameEs: 'Corriente de Humboldt (Perú)',
    nameUk: 'Течія Гумбольдта (Перуанська)',
    path: [(lat: -5.0, lon: -81.5), (lat: -20.0, lon: -75.0), (lat: -35.0, lon: -73.0)],
    speedKtMin: 0.4, speedKtMax: 0.9,
    noteEn: 'Cold, nutrient-rich current north along the Chile/Peru coast. Year-round; disrupted during El Niño.',
    noteSk: 'Studený, na živiny bohatý prúd na sever pozdĺž pobrežia Čile/Peru. Celoročne; narušený počas El Niño.',
    noteDe: 'Kalter, nährstoffreicher Strom nordwärts entlang der Küste Chiles/Perus. Ganzjährig; gestört während El Niño.',
    noteEs: 'Corriente fría y rica en nutrientes hacia el norte por la costa de Chile/Perú. Todo el año; alterada durante El Niño.',
    noteUk: 'Холодна, багата на поживні речовини течія на північ уздовж узбережжя Чилі/Перу. Цілий рік; порушується під час Ель-Ніньйо.',
  ),
  OceanCurrent(
    id: 'east_australian_current',
    nameEn: 'East Australian Current', nameSk: 'Východoaustrálsky prúd', nameDe: 'Ostaustralienstrom',
    nameEs: 'Corriente de Australia Oriental', nameUk: 'Східноавстралійська течія',
    path: [(lat: -18.0, lon: 147.0), (lat: -28.0, lon: 154.0), (lat: -38.0, lon: 150.0)],
    speedKtMin: 1.0, speedKtMax: 4.5,
    noteEn: 'Warm current south along Australia\'s east coast (Great Barrier Reef to Tasman Sea). Year-round, strongest in summer (Dec–Mar).',
    noteSk: 'Teplý prúd na juh popri východnom pobreží Austrálie (od Veľkej bariérovej útesu po Tasmanovo more). Celoročne, najsilnejší v lete (dec–mar).',
    noteDe: 'Warmer Strom südwärts entlang der australischen Ostküste (Great Barrier Reef bis Tasmansee). Ganzjährig, am stärksten im Sommer (Dez–Mär).',
    noteEs: 'Corriente cálida hacia el sur por la costa este de Australia (Gran Barrera de Coral al Mar de Tasmania). Todo el año, más fuerte en verano (dic–mar).',
    noteUk: 'Тепла течія на південь уздовж східного узбережжя Австралії (від Великого Бар\'єрного рифу до Тасманового моря). Цілий рік, найсильніша влітку (груд.–бер.).',
  ),
  OceanCurrent(
    id: 'agulhas_current',
    nameEn: 'Agulhas Current', nameSk: 'Agulhaský prúd', nameDe: 'Agulhasstrom',
    nameEs: 'Corriente de Agulhas', nameUk: 'Течія Агульяс',
    path: [(lat: -25.0, lon: 35.5), (lat: -30.0, lon: 31.0), (lat: -35.5, lon: 22.0)],
    speedKtMin: 2.0, speedKtMax: 5.0,
    noteEn: 'Fast, warm current south along South Africa\'s east coast, retroflecting at the Agulhas Bank. Year-round; can create dangerous seas against SW swell.',
    noteSk: 'Rýchly, teplý prúd na juh pozdĺž východného pobrežia JAR, stáčajúci sa späť pri Agulhaskej lavici. Celoročne; môže vytvárať nebezpečné vlny proti juhozápadnej vlne.',
    noteDe: 'Schneller, warmer Strom südwärts entlang der südafrikanischen Ostküste, Umkehr an der Agulhas-Bank. Ganzjährig; kann bei SW-Dünung gefährliche See erzeugen.',
    noteEs: 'Corriente rápida y cálida hacia el sur por la costa este de Sudáfrica, con retroflexión en el Banco de Agulhas. Todo el año; puede crear mar peligroso contra la marejada SO.',
    noteUk: 'Швидка тепла течія на південь уздовж східного узбережжя ПАР з ретрофлексією на банці Агульяс. Цілий рік; може створювати небезпечне хвилювання проти зибу з ПдЗ.',
  ),
  OceanCurrent(
    id: 'somali_current',
    nameEn: 'Somali Current', nameSk: 'Somálsky prúd', nameDe: 'Somalistrom',
    nameEs: 'Corriente de Somalia', nameUk: 'Сомалійська течія',
    path: [(lat: 2.0, lon: 48.0), (lat: 8.0, lon: 50.0), (lat: 12.0, lon: 52.0)],
    speedKtMin: 1.0, speedKtMax: 7.0,
    noteEn: 'Monsoon-driven, reverses seasonally: strong NE flow (up to 7 kt) during SW monsoon (Jun–Sep), weaker/reversed during NE monsoon (Dec–Feb).',
    noteSk: 'Riadený monzúnom, sezónne mení smer: silné severovýchodné prúdenie (do 7 kt) počas juhozápadného monzúnu (jún–sep), slabšie/opačné počas severovýchodného monzúnu (dec–feb).',
    noteDe: 'Monsungetrieben, saisonal umkehrend: starke NO-Strömung (bis 7 kn) während SW-Monsun (Jun–Sep), schwächer/umgekehrt während NO-Monsun (Dez–Feb).',
    noteEs: 'Impulsada por el monzón, se invierte estacionalmente: fuerte flujo NE (hasta 7 kt) durante el monzón SO (jun–sep), más débil/invertido durante el monzón NE (dic–feb).',
    noteUk: 'Мусонна, сезонно змінює напрямок: сильна ПнСх течія (до 7 вузлів) під час ПдЗх мусону (черв.–вер.), слабша/зворотна під час ПнСх мусону (груд.–лют.).',
  ),
  OceanCurrent(
    id: 'north_equatorial_pacific',
    nameEn: 'North Equatorial Current (Pacific)', nameSk: 'Severný rovníkový prúd (Tichomorie)',
    nameDe: 'Nordäquatorialstrom (Pazifik)', nameEs: 'Corriente Ecuatorial del Norte (Pacífico)',
    nameUk: 'Північна екваторіальна течія (Тихий океан)',
    path: [(lat: 15.0, lon: -140.0), (lat: 13.0, lon: -170.0), (lat: 12.0, lon: 150.0)],
    speedKtMin: 0.4, speedKtMax: 0.9,
    noteEn: 'Westward flow across the tropical North Pacific, feeding the Kuroshio. Year-round.',
    noteSk: 'Prúdenie na západ cez tropický severný Tichý oceán, napája prúd Kuroshio. Celoročne.',
    noteDe: 'Westströmung durch den tropischen Nordpazifik, speist den Kuroshio. Ganzjährig.',
    noteEs: 'Flujo hacia el oeste a través del Pacífico tropical norte, alimenta la Kuroshio. Todo el año.',
    noteUk: 'Течія на захід через тропічну північну частину Тихого океану, живить течію Куросіо. Цілий рік.',
  ),
];
